config/routes.rb
Rails.application.routes.draw do

  namespace :boarding do
    get '/informations' => "informations#index", as: :informations
    get '/professional' => "professional#index", as: :professional
    get '/design' => "design#index", as: :design
    get '/domain' => "domain#index", as: :domain
  end

  get '/dashboard' => 'dashboard#index', as: :dashboard
  resources :profiles
  devise_for :accounts,
  :path => "auth",
  :path_names => {
    :sign_in => 'login',
    :sign_out => 'logout',
    :password => 'secret',
    :confirmation => 'verification',
    :unlock => 'unblock',
    # :registration => 'register',
    :sign_up => 'register'
  }
  root to: 'public#main'
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :confirmable
  has_one :profile
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :account
end

app/controllers/accounts/passwords_controller.rb
# frozen_string_literal: true

class Accounts::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/accounts/sessions_controller.rb
# frozen_string_literal: true

class Accounts::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/accounts/unlocks_controller.rb
# frozen_string_literal: true

class Accounts::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:first_name, :last_name, :url]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/boarding/design_controller.rb
class Boarding::DesignController < ApplicationController
  	layout "boarding"
  	def index
  	end
end

app/controllers/boarding/domain_controller.rb
class Boarding::DomainController < ApplicationController
  	layout "boarding"
  	def index
  	end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  include Devise::Controllers::Helpers
  def index
    
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  


  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:title)
    end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def main
  	@user = current_account
  	return @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boarding/design_helper.rb
module Boarding::DesignHelper
end

app/helpers/boarding/domain_helper.rb
module Boarding::DomainHelper
end

app/helpers/boarding/informations_helper.rb
module Boarding::InformationsHelper
end

app/helpers/boarding/professional_helper.rb
module Boarding::ProfessionalHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Whizzo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,700&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/6527645c57.js" crossorigin="anonymous"></script>
  </head>



  <body class="font-sans bg-white antialiased text-sm">



      <% if notice %>
        <div class="bg-whizzo-500 border-t-4 border-whizzo-400 text-teal-darkest px-4 py-3" role="alert">
          <div>
            <div>
              <p class="text-sm text-white font-semibold"><%= notice %></p>
            </div>
          </div>
        </div>
        <% end %>
        <% if alert %>
        <div class="bg-red-400 border-t-4 border-red-600 text-teal-darkest px-4 py-3" role="alert">
          <div>
              <p class="text-sm text-white font-semibold"><%= alert %></p>
            </div>
          </div>
        </div>
      <% end %>


    <%= render "layouts/nav/public" %>

    <% if !@user.profile %>
      <div class="bg-whizzo-300 border-t-4 border-whizze-400 text-teal-darkest px-4 py-3" role="alert">
        <div>
            <p class="sm:px-20 text-sm text-white font-semibold"><span class="bg-white text-whizzo-400 py-2 px-3 mr-2 rounded-full">20%</span> Complete your <%= link_to 'profile now', boarding_informations_path, class: "no-underline border-b-2 hover:border-transparent" %></p>
          </div>
      </div>
    <% end %>


    <main class="px-12 py-4 sm:px-24 sm:py-6">
      <%= yield %>
    </main>


    <footer class="mt-40 px-12 py-4 sm:px-24 sm:py-6 bg-whizzo-100">
      <div class="py-10 flex flex-col sm:flex-row sm:justify-between sm:items-center">
        <div>
          <a href="#">
            <img class="w-24" src="<%= asset_path('logo.png') %>" alt="Whizzo.co">
          </a>
          <p class="w-full sm:w-1/3 mt-4 text-whizzo-400">
            a platform where freelancers, entrepreneurs, and side hustlers can expand their audience and attract new clients.
          </p>
        </div>
        <div>
          <p class="mt-12 sm:mt-0 text-whizzo-400 font-normal">&copy; 2019 <a href="#">whizzo.co™</a></p>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/layouts/boarding.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Whizzo - Profile onboarding</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,700&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/6527645c57.js" crossorigin="anonymous"></script>
  </head>



  <body class="font-sans bg-white antialiased text-sm">



      <% if notice %>
        <div class="bg-whizzo-500 border-t-4 border-whizzo-400 text-teal-darkest px-4 py-3" role="alert">
          <div>
            <div>
              <p class="text-sm text-white font-semibold"><%= notice %></p>
            </div>
          </div>
        </div>
        <% end %>
        <% if alert %>
        <div class="bg-red-400 border-t-4 border-red-600 text-teal-darkest px-4 py-3" role="alert">
          <div>
              <p class="text-sm text-white font-semibold"><%= alert %></p>
            </div>
          </div>
        </div>
      <% end %>

      <section class="px-12 md:px-32">

        <%= yield %>

      </section>

      

  </body>
</html>

app/views/layouts/nav/_public.html.erb
<header class="flex flex-col sm:flex-row sm:justify-between items-center px-12 py-4 sm:px-24 sm:py-6">
  <div>
    <a href="/">
      <img class="w-24" src="<%= asset_path('logo.png') %>" alt="Whizzo.co">
    </a>
  </div>
  <nav class="mt-6 sm:mt-0 text-whizzo-400 font-medium">
    <% if account_signed_in? %>
      <%= link_to "Dashboard", dashboard_path, :class=>"ml-4 hover:bg-transparent hover:text-whizzo-300" %>
      <%= link_to "Sign out", destroy_account_session_path, method: :delete, :class=>"ml-4 hover:bg-transparent hover:text-whizzo-300" %>
    <% else %>
      <a href="#" class="hover:bg-transparent hover:text-whizzo-300">Features</a>
      <a href="#" class="ml-4 hover:bg-transparent hover:text-whizzo-300">Pricing</a>
      <%= link_to "Sign in", new_account_session_path, :class=>"ml-4 hover:bg-transparent hover:text-whizzo-300" %>
    <% end %>
  </nav>

  <% if account_signed_in? %>
    <a href="#" class="hidden sm:block text-white font-semibold bg-whizzo-300 py-2 px-4 rounded-lg hover:bg-whizzo-400 hover:bg-transparent text-center visited:text-white">Visit your profile <i class="ml-2 fas fa-external-link-alt"></i></a>
  <% else %>
    <%= link_to "Create your free profile", new_account_registration_url, :class=>"hidden sm:block text-white font-semibold bg-whizzo-300 py-2 px-4 rounded-lg hover:bg-whizzo-400 hover:bg-transparent text-center visited:text-white" %>
  <% end %>

</header>